{% set name = "awslambdaric" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/awslambdaric-{{ version }}.tar.gz
  sha256: bdaab2cb0c5a869aad726a30521066e7cf4586048c67e46c0d11e14ecc2cf663

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - autoconf
    - automake
    - make  # [not win]
    - ninja  # [win]
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - importlib-metadata ~=2.0
    - simplejson ==3.17.2

test:
  imports:
    - awslambdaric
    - test
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/aws-lambda-python-runtime-interface-client
  summary: AWS Lambda Runtime Interface Client for Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MichelML
