{% set name = "awslambdaric" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/awslambdaric-{{ version }}.tar.gz
  sha256: bdaab2cb0c5a869aad726a30521066e7cf4586048c67e46c0d11e14ecc2cf663

build:
  number: 0
  skip: true   # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - importlib-metadata ~=2.0  # [py<38]
    - python
    - simplejson ==3.17.2

test:
  imports:
    - awslambdaric
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/aws-lambda-python-runtime-interface-client
  summary: AWS Lambda Runtime Interface Client for Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MichelML
